<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Landingpage extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        //if ($this->session->userdata('logged_in') !== TRUE) {
           // redirect('login');
        //}
    }

    function index()
    {
        $data['_view'] = 'tamplate/dashboard';
		$this->load->view('landing/landingpage');
    }
}
